// packages/svelte/example/src/components/RouterView.svelte
<script lang="ts">
  import { onMount, onDestroy } from 'svelte'
  import { getEngine } from '@ldesign/engine-svelte'

  const engine = getEngine()
  let CurrentComponent: any = null
  let unsubscribe: (() => void) | undefined

  onMount(() => {
    if (!engine.router) {
      console.warn('Router not available')
      return
    }

    const updateComponent = () => {
      if (engine.router) {
        const route = engine.router.getCurrentRoute()
        if (route.value?.component) {
          CurrentComponent = route.value.component
        }
      }
    }

    updateComponent()
    unsubscribe = engine.events.on('router:navigated', updateComponent)
  })

  onDestroy(() => {
    if (unsubscribe) unsubscribe()
  })
</script>

<div class="router-view">
  {#if CurrentComponent}
    <svelte:component this={CurrentComponent} />
  {:else}
    <div>Loading...</div>
  {/if}
</div>

// packages/solid/example/src/components/RouterView.tsx
import { createSignal, createEffect, onCleanup, Component, Show } from 'solid-js'
import { Dynamic } from 'solid-js/web'
import { useEngine } from '@ldesign/engine-solid'

export default function RouterView() {
  const engine = useEngine()
  const [currentComponent, setCurrentComponent] = createSignal<Component | null>(null)

  createEffect(() => {
    if (!engine.router) {
      return
    }

    const updateComponent = () => {
      const route = engine.router!.getCurrentRoute()
      if (route.value?.component) {
        const comp = route.value.component as Component
        // 使用函数包装来设置组件，因为组件本身就是函数
        setCurrentComponent(() => comp)
      }
    }

    // 初始化
    updateComponent()

    // 监听路由变化
    const unsubscribe = engine.events.on('router:navigated', (data: any) => {
      updateComponent()
    })

    onCleanup(() => {
      if (unsubscribe) unsubscribe()
    })
  })

  return (
    <div class="router-view">
      <Show when={currentComponent()} fallback={<div>Loading...</div>}>
        <Dynamic component={currentComponent()!} />
      </Show>
    </div>
  )
}
