// packages/solid/src/components/EngineProvider.tsx
/**
 * Solid Engine Provider Component
 * 
 * 提供引擎上下文
 * 
 * @module components/EngineProvider
 */

import { type JSX } from 'solid-js'
import type { CoreEngine } from '@ldesign/engine-core'
import { EngineContext } from '../hooks/useEngine'

/**
 * EngineProvider Props
 */
export interface EngineProviderProps {
  /** 引擎实例 */
  engine: CoreEngine
  /** 子组件 */
  children: JSX.Element
}

/**
 * Engine Provider 组件
 * 
 * 提供引擎上下文给子组件
 * 
 * @example
 * ```tsx
 * import { EngineProvider } from '@ldesign/engine-solid'
 * import { createCoreEngine } from '@ldesign/engine-core'
 * 
 * const engine = createCoreEngine({ name: 'my-app' })
 * 
 * function App() {
 *   return (
 *     <EngineProvider engine={engine}>
 *       <YourApp />
 *     </EngineProvider>
 *   )
 * }
 * ```
 */
export function EngineProvider(props: EngineProviderProps): JSX.Element {
  return (
    <EngineContext.Provider value={props.engine}>
      {props.children}
    </EngineContext.Provider>
  )
}

// packages/svelte/src/components/EngineProvider.svelte
<script lang="ts">
/**
 * Svelte Engine Provider Component
 * 
 * 提供引擎上下文
 * 
 * @module components/EngineProvider
 */
import { setContext } from 'svelte'
import type { CoreEngine } from '@ldesign/engine-core'
import { ENGINE_CONTEXT_KEY } from '../engine-app'

/**
 * Engine Provider Props
 */
export let engine: CoreEngine

// 设置引擎上下文
setContext(ENGINE_CONTEXT_KEY, engine)
</script>

<slot />
