// packages/qwik/example/src/components/RouterView.tsx
import { component$, useSignal, useVisibleTask$ } from '@builder.io/qwik'
import { getEngine } from '@ldesign/engine-qwik'

export default component$(() => {
  const CurrentComponent = useSignal<any>(null)
  const loading = useSignal(true)

  useVisibleTask$(() => {
    try {
      const engine = getEngine()
      if (!engine.router) {
        console.warn('Router not available')
        loading.value = false
        return
      }

      const updateComponent = () => {
        if (engine.router) {
          const route = engine.router.getCurrentRoute()
          if (route.value?.component) {
            CurrentComponent.value = route.value.component
            loading.value = false
          }
        }
      }

      updateComponent()
      const unsubscribe = engine.events.on('router:navigated', updateComponent)
      return () => unsubscribe()
    } catch (error) {
      console.warn('Engine not ready yet:', error)
      loading.value = false
    }
  })

  return (
    <div class="router-view">
      {loading.value ? (
        <div class="loading">
          <div class="spinner"></div>
          <p>Loading...</p>
        </div>
      ) : CurrentComponent.value ? (
        <CurrentComponent.value />
      ) : (
        <div class="error">
          <h2>404 - Page Not Found</h2>
          <p>The requested page could not be found.</p>
        </div>
      )}

      <style>{`
        .router-view {
          min-height: calc(100vh - 200px);
        }

        .loading {
          display: flex;
          flex-direction: column;
          align-items: center;
          justify-content: center;
          min-height: 400px;
          color: #666;
        }

        .spinner {
          width: 50px;
          height: 50px;
          border: 4px solid #f3f4f6;
          border-top-color: #667eea;
          border-radius: 50%;
          animation: spin 1s linear infinite;
        }

        @keyframes spin {
          to {
            transform: rotate(360deg);
          }
        }

        .loading p {
          margin-top: 1rem;
          font-size: 1.1rem;
        }

        .error {
          text-align: center;
          padding: 4rem 2rem;
        }

        .error h2 {
          font-size: 2rem;
          color: #333;
          margin: 0 0 1rem;
        }

        .error p {
          color: #666;
          font-size: 1.1rem;
        }
      `}</style>
    </div>
  )
})

// packages/vue2/example/src/components/RouterView.vue
<template>
  <div class="router-view">
    <component :is="currentComponent" v-if="currentComponent" />
    <div v-else class="loading">加载中...</div>
  </div>
</template>

<script>
import { getEngine } from '@ldesign/engine-vue2'
import Home from '../pages/Home.vue'
import About from '../pages/About.vue'
import User from '../pages/User.vue'

const routes = {
  '/': Home,
  '/about': About,
  '/user/:id': User,
}

export default {
  name: 'RouterView',
  data() {
    return {
      currentComponent: null,
      unsubscribe: null,
    }
  },
  created() {
    this.updateComponent()
    
    const engine = getEngine()
    this.unsubscribe = engine.events.on('router:navigated', () => {
      this.updateComponent()
    })
  },
  beforeDestroy() {
    if (this.unsubscribe) {
      this.unsubscribe()
    }
  },
  methods: {
    updateComponent() {
      const engine = getEngine()
      if (engine.router) {
        const route = engine.router.getCurrentRoute()
        const path = route.value?.path || '/'
        
        // 简单的路由匹配
        if (routes[path]) {
          this.currentComponent = routes[path]
        } else if (path.startsWith('/user/')) {
          this.currentComponent = User
        } else {
          this.currentComponent = Home
        }
      } else {
        this.currentComponent = Home
      }
    },
  },
}
</script>

<style scoped>
.router-view {
  min-height: 400px;
}

.loading {
  display: flex;
  justify-content: center;
  align-items: center;
  min-height: 400px;
  font-size: 1.2rem;
  color: #666;
}
</style>
