// packages/qwik/example/src/pages/User.tsx
import { component$, useSignal, useVisibleTask$, $ } from '@builder.io/qwik'
import { getEngine } from '@ldesign/engine-qwik'

interface User {
  id: string
  name: string
  email: string
  role: string
  avatar: string
}

const mockUsers: Record<string, User> = {
  '1': { id: '1', name: '张三', email: 'zhangsan@example.com', role: '管理员', avatar: '👨‍💼' },
  '2': { id: '2', name: '李四', email: 'lisi@example.com', role: '开发者', avatar: '👨‍💻' },
  '3': { id: '3', name: '王五', email: 'wangwu@example.com', role: '设计师', avatar: '👨‍🎨' },
}

export default component$(() => {
  const userId = useSignal('1')
  const user = useSignal<User>(mockUsers['1'])
  const engine = getEngine()

  useVisibleTask$(() => {
    if (engine.router) {
      const route = engine.router.getCurrentRoute()
      userId.value = route.value?.params?.id || '1'
      user.value = mockUsers[userId.value] || mockUsers['1']
      
      const unsubscribe = engine.events.on('router:navigated', () => {
        if (engine.router) {
          const route = engine.router.getCurrentRoute()
          userId.value = route.value?.params?.id || '1'
          user.value = mockUsers[userId.value] || mockUsers['1']
        }
      })
      return () => unsubscribe()
    } else {
      user.value = mockUsers[userId.value]
    }
  })

  const switchUser = $((id: string) => {
    if (engine.router) {
      engine.router.push(`/user/${id}`)
    }
  })

  return (
    <div class="user">
      <div class="header">
        <h1>👤 用户详情</h1>
      </div>

      <div class="user-card">
        <div class="avatar">{user.value.avatar}</div>
        <h2 class="user-name">{user.value.name}</h2>
        <p class="user-email">{user.value.email}</p>
        <span class="user-role">{user.value.role}</span>

        <div class="user-info">
          <div class="info-item">
            <span class="info-label">用户 ID</span>
            <span class="info-value">{user.value.id}</span>
          </div>
          <div class="info-item">
            <span class="info-label">姓名</span>
            <span class="info-value">{user.value.name}</span>
          </div>
          <div class="info-item">
            <span class="info-label">邮箱</span>
            <span class="info-value">{user.value.email}</span>
          </div>
          <div class="info-item">
            <span class="info-label">角色</span>
            <span class="info-value">{user.value.role}</span>
          </div>
        </div>

        <div class="user-selector">
          <button
            class={userId.value === '1' ? 'active' : ''}
            onClick$={() => switchUser('1')}
          >
            用户 1
          </button>
          <button
            class={userId.value === '2' ? 'active' : ''}
            onClick$={() => switchUser('2')}
          >
            用户 2
          </button>
          <button
            class={userId.value === '3' ? 'active' : ''}
            onClick$={() => switchUser('3')}
          >
            用户 3
          </button>
        </div>
      </div>

      <style>{`
        .user {
          padding: 2rem;
          max-width: 600px;
          margin: 0 auto;
        }

        .header {
          text-align: center;
          margin-bottom: 2rem;
        }

        .header h1 {
          margin: 0 0 0.5rem;
          font-size: 2rem;
          color: #333;
        }

        .user-card {
          background: white;
          padding: 2rem;
          border-radius: 12px;
          box-shadow: 0 4px 12px rgba(0, 0, 0, 0.1);
          text-align: center;
        }

        .avatar {
          font-size: 5rem;
          margin-bottom: 1rem;
        }

        .user-name {
          font-size: 1.8rem;
          font-weight: bold;
          color: #333;
          margin: 0 0 0.5rem;
        }

        .user-email {
          color: #666;
          margin: 0 0 1rem;
        }

        .user-role {
          display: inline-block;
          padding: 0.5rem 1rem;
          background: #667eea;
          color: white;
          border-radius: 20px;
          font-size: 0.9rem;
          margin-bottom: 2rem;
        }

        .user-info {
          text-align: left;
          margin-top: 2rem;
          padding-top: 2rem;
          border-top: 1px solid #f0f0f0;
        }

        .info-item {
          display: flex;
          justify-content: space-between;
          padding: 0.75rem 0;
          border-bottom: 1px solid #f0f0f0;
        }

        .info-item:last-child {
          border-bottom: none;
        }

        .info-label {
          font-weight: 600;
          color: #333;
        }

        .info-value {
          color: #666;
        }

        .user-selector {
          display: flex;
          gap: 1rem;
          justify-content: center;
          margin-top: 2rem;
        }

        button {
          padding: 0.75rem 1.5rem;
          font-size: 1rem;
          border: none;
          border-radius: 6px;
          cursor: pointer;
          background: #f3f4f6;
          color: #333;
          transition: all 0.3s;
        }

        button:hover {
          background: #e5e7eb;
        }

        button.active {
          background: #667eea;
          color: white;
        }
      `}</style>
    </div>
  )
})

// packages/angular/example/src/app/pages/user.component.ts
/**
 * Angular Engine 示例 - 用户详情页面组件
 */
import { Component, OnInit } from '@angular/core'
import { CommonModule } from '@angular/common'

interface User {
  id: number
  name: string
  email: string
  role: string
  avatar: string
}

@Component({
  selector: 'app-user',
  standalone: true,
  imports: [CommonModule],
  template: `
    <div class="page">
      <h2>👤 用户详情</h2>
      <p>展示路由参数的使用</p>

      <div class="card">
        <h3>当前用户 ID: {{ userId }}</h3>
        <div class="user-profile" *ngIf="currentUser">
          <div class="user-avatar">{{ currentUser.avatar }}</div>
          <div class="user-info">
            <h4>{{ currentUser.name }}</h4>
            <p>{{ currentUser.email }}</p>
            <span class="user-role">{{ currentUser.role }}</span>
          </div>
        </div>
        <p class="hint" *ngIf="!currentUser">用户未找到</p>
      </div>

      <div class="card">
        <h3>切换用户</h3>
        <div class="user-switcher">
          <button 
            *ngFor="let user of users" 
            (click)="switchUser(user.id)"
            [class.active]="userId === user.id.toString()"
          >
            {{ user.avatar }} {{ user.name }}
          </button>
        </div>
      </div>

      <div class="card">
        <h3>📋 用户信息</h3>
        <table class="info-table" *ngIf="currentUser">
          <tr>
            <td><strong>ID:</strong></td>
            <td>{{ currentUser.id }}</td>
          </tr>
          <tr>
            <td><strong>姓名:</strong></td>
            <td>{{ currentUser.name }}</td>
          </tr>
          <tr>
            <td><strong>邮箱:</strong></td>
            <td>{{ currentUser.email }}</td>
          </tr>
          <tr>
            <td><strong>角色:</strong></td>
            <td>{{ currentUser.role }}</td>
          </tr>
        </table>
      </div>
    </div>
  `,
  styles: [`
    .page {
      animation: fadeIn 0.3s ease-in;
    }

    @keyframes fadeIn {
      from {
        opacity: 0;
        transform: translateY(10px);
      }
      to {
        opacity: 1;
        transform: translateY(0);
      }
    }

    .card {
      background: white;
      border-radius: 8px;
      padding: 1.5rem;
      margin-bottom: 1.5rem;
      box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
    }

    .card h3 {
      margin-top: 0;
      margin-bottom: 1rem;
      color: #333;
    }

    .user-profile {
      display: flex;
      align-items: center;
      gap: 1.5rem;
      padding: 1rem;
      background: linear-gradient(135deg, #dd003115 0%, #c3002f15 100%);
      border-radius: 8px;
    }

    .user-avatar {
      width: 80px;
      height: 80px;
      border-radius: 50%;
      background: linear-gradient(135deg, #dd0031 0%, #c3002f 100%);
      display: flex;
      align-items: center;
      justify-content: center;
      font-size: 2.5rem;
      flex-shrink: 0;
    }

    .user-info h4 {
      margin: 0 0 0.5rem 0;
      color: #333;
    }

    .user-info p {
      margin: 0 0 0.5rem 0;
      color: #666;
    }

    .user-role {
      display: inline-block;
      padding: 0.25rem 0.75rem;
      background: #dd0031;
      color: white;
      border-radius: 12px;
      font-size: 0.85rem;
    }

    .user-switcher {
      display: flex;
      flex-wrap: wrap;
      gap: 0.75rem;
    }

    .user-switcher button {
      padding: 0.75rem 1.25rem;
      border: 2px solid #ddd;
      border-radius: 8px;
      background: white;
      cursor: pointer;
      transition: all 0.3s ease;
      font-size: 1rem;
    }

    .user-switcher button:hover {
      border-color: #dd0031;
      transform: translateY(-2px);
      box-shadow: 0 4px 8px rgba(221, 0, 49, 0.2);
    }

    .user-switcher button.active {
      background: linear-gradient(135deg, #dd0031 0%, #c3002f 100%);
      color: white;
      border-color: #dd0031;
    }

    .hint {
      color: #666;
      font-size: 0.9rem;
      margin-top: 0.5rem;
    }

    .info-table {
      width: 100%;
      border-collapse: collapse;
    }

    .info-table tr {
      border-bottom: 1px solid #eee;
    }

    .info-table td {
      padding: 0.75rem 0;
    }

    .info-table td:first-child {
      width: 30%;
      color: #666;
    }
  `]
})
export class UserComponent implements OnInit {
  userId = '1'
  currentUser: User | null = null

  users: User[] = [
    { id: 1, name: '张三', email: 'zhangsan@example.com', role: '管理员', avatar: '👨‍💼' },
    { id: 2, name: '李四', email: 'lisi@example.com', role: '开发者', avatar: '👨‍💻' },
    { id: 3, name: '王五', email: 'wangwu@example.com', role: '设计师', avatar: '👨‍🎨' },
  ]

  ngOnInit() {
    // 从路由获取用户 ID
    if (typeof window !== 'undefined' && (window as any).__ENGINE__) {
      const engine = (window as any).__ENGINE__
      if (engine.router) {
        const route = engine.router.getCurrentRoute()
        this.userId = route.value?.params?.id || '1'
        this.updateCurrentUser()

        // 监听路由变化
        engine.events.on('router:navigated', () => {
          const newRoute = engine.router.getCurrentRoute()
          this.userId = newRoute.value?.params?.id || '1'
          this.updateCurrentUser()
        })
      }
    }
  }

  updateCurrentUser() {
    const id = parseInt(this.userId, 10)
    this.currentUser = this.users.find(u => u.id === id) || null
  }

  switchUser(id: number) {
    if (typeof window !== 'undefined' && (window as any).__ENGINE__) {
      const engine = (window as any).__ENGINE__
      if (engine.router) {
        engine.router.push(`/user/${id}`)
      }
    }
  }
}
