// packages/solid/example/src/components/Navigation.tsx
import { createSignal, createEffect, onCleanup, JSX } from 'solid-js'
import { useEngine } from '@ldesign/engine-solid'

interface NavLinkProps {
  to: string
  children: JSX.Element
}

function NavLink(props: NavLinkProps) {
  const engine = useEngine()
  const [isActive, setIsActive] = createSignal(false)

  const checkActive = () => {
    if (!engine.router) return
    const route = engine.router.getCurrentRoute()
    const currentPath = route.value?.path || '/'
    setIsActive(currentPath === props.to || currentPath.startsWith(props.to + '/'))
  }

  createEffect(() => {
    checkActive()
    const unsubscribe = engine.events.on('router:navigated', checkActive)
    onCleanup(() => {
      if (unsubscribe) unsubscribe()
    })
  })

  const handleClick = (e: MouseEvent) => {
    e.preventDefault()
    if (engine.router) {
      engine.router.push(props.to)
    }
  }

  return (
    <a
      href={props.to}
      onClick={handleClick}
      classList={{ 'nav-link': true, active: isActive() }}
    >
      {props.children}
    </a>
  )
}

export default function Navigation() {
  return (
    <nav class="navigation">
      <div class="nav-brand">
        <h1>🚀 Solid + LDesign Engine</h1>
      </div>
      <div class="nav-links">
        <NavLink to="/">🏠 首页</NavLink>
        <NavLink to="/about">ℹ️ 关于</NavLink>
        <NavLink to="/user/1">👤 用户</NavLink>
      </div>
    </nav>
  )
}

// packages/react/example/src/components/Navigation.tsx
import React from 'react'
import { useEngine } from '@ldesign/engine-react'

interface NavLinkProps {
  to: string
  children: React.ReactNode
}

function NavLink({ to, children }: NavLinkProps) {
  const engine = useEngine()
  const [isActive, setIsActive] = React.useState(false)

  React.useEffect(() => {
    if (!engine.router) return

    const checkActive = () => {
      const route = engine.router.getCurrentRoute()
      const currentPath = route.value?.path || '/'
      setIsActive(currentPath === to || currentPath.startsWith(to + '/'))
    }

    checkActive()

    // 监听路由变化
    const unsubscribe = engine.events.on('router:navigated', checkActive)
    return () => unsubscribe()
  }, [engine.router, to])

  const handleClick = (e: React.MouseEvent) => {
    e.preventDefault()
    if (engine.router) {
      engine.router.push(to)
    }
  }

  return (
    <a
      href={to}
      onClick={handleClick}
      className={`nav-link ${isActive ? 'active' : ''}`}
    >
      {children}
    </a>
  )
}

function Navigation() {
  return (
    <nav className="navigation">
      <div className="nav-brand">
        <span className="logo">🚀</span>
        <span className="brand-name">LDesign Engine</span>
      </div>
      <div className="nav-links">
        <NavLink to="/">🏠 首页</NavLink>
        <NavLink to="/about">ℹ️ 关于</NavLink>
        <NavLink to="/user/1">👤 用户</NavLink>
      </div>
    </nav>
  )
}

export default Navigation
