// packages/preact/example/src/components/Navigation.tsx
import { h } from 'preact'
import { useState, useEffect } from 'preact/hooks'
import { useEngine } from '@ldesign/engine-preact'

interface NavLinkProps {
  to: string
  children: any
}

function NavLink({ to, children }: NavLinkProps) {
  const engine = useEngine()
  const [isActive, setIsActive] = useState(false)

  useEffect(() => {
    if (!engine.router) return

    const checkActive = () => {
      const route = engine.router!.getCurrentRoute()
      const currentPath = route.value?.path || '/'
      setIsActive(currentPath === to || currentPath.startsWith(to + '/'))
    }

    checkActive()
    const unsubscribe = engine.events.on('router:navigated', checkActive)

    return () => {
      if (unsubscribe) unsubscribe()
    }
  }, [engine.router, to])

  const handleClick = (e: Event) => {
    e.preventDefault()
    if (engine.router) {
      engine.router.push(to)
    }
  }

  return (
    <a href={to} onClick={handleClick} class={`nav-link ${isActive ? 'active' : ''}`}>
      {children}
    </a>
  )
}

export default function Navigation() {
  return (
    <nav class="navigation">
      <div class="nav-brand">
        <h1>🚀 Preact + LDesign Engine</h1>
      </div>
      <div class="nav-links">
        <NavLink to="/">🏠 首页</NavLink>
        <NavLink to="/about">ℹ️ 关于</NavLink>
        <NavLink to="/user/1">👤 用户</NavLink>
      </div>
    </nav>
  )
}

// packages/svelte/example/src/components/Navigation.svelte
<script lang="ts">
  import { onMount, onDestroy } from 'svelte'
  import { getEngine } from '@ldesign/engine-svelte'

  const engine = getEngine()
  let currentPath = '/'
  let unsubscribe: (() => void) | undefined

  onMount(() => {
    if (engine.router) {
      const route = engine.router.getCurrentRoute()
      currentPath = route.value?.path || '/'
      
      unsubscribe = engine.events.on('router:navigated', () => {
        if (engine.router) {
          const route = engine.router.getCurrentRoute()
          currentPath = route.value?.path || '/'
        }
      })
    }
  })

  onDestroy(() => {
    if (unsubscribe) unsubscribe()
  })

  function navigate(path: string, event: MouseEvent) {
    event.preventDefault()
    if (engine.router) {
      engine.router.push(path)
    }
  }

  function isActive(path: string): boolean {
    return currentPath === path || currentPath.startsWith(path + '/')
  }
</script>

<nav class="navigation">
  <div class="nav-brand">
    <h1>🚀 Svelte + LDesign Engine</h1>
  </div>
  <div class="nav-links">
    <a 
      href="/" 
      on:click={(e) => navigate('/', e)} 
      class="nav-link"
      class:active={isActive('/')}
    >
      🏠 首页
    </a>
    <a 
      href="/about" 
      on:click={(e) => navigate('/about', e)}
      class="nav-link"
      class:active={isActive('/about')}
    >
      ℹ️ 关于
    </a>
    <a 
      href="/user/1" 
      on:click={(e) => navigate('/user/1', e)}
      class="nav-link"
      class:active={isActive('/user')}
    >
      👤 用户
    </a>
  </div>
</nav>
