// packages/qwik/src/utils/helpers.ts
/**
 * Qwik 辅助函数
 */

import type { CoreEngine } from '@ldesign/engine-core'

/**
 * 获取引擎实例
 * 
 * 在 Qwik 组件中使用此函数来访问引擎
 * 
 * @returns 引擎实例
 * @throws 如果引擎未找到则抛出错误
 * 
 * @example
 * ```tsx
 * import { component$ } from '@builder.io/qwik'
 * import { getEngine } from '@ldesign/engine-qwik'
 * 
 * export default component$(() => {
 *   const engine = getEngine()
 *   
 *   return <div>Engine: {engine.config.name}</div>
 * })
 * ```
 */
export function getEngine(): CoreEngine {
  const engine = (window as any).__ldesignEngine as CoreEngine
  if (!engine) {
    throw new Error('LDesign Engine not found. Make sure you have called createEngineApp.')
  }
  return engine
}

// packages/lit/src/utils/helpers.ts
/**
 * Lit 引擎辅助函数
 */

import type { CoreEngine } from '@ldesign/engine-core'

/**
 * 使用引擎
 * 
 * 在组件中获取引擎实例的辅助函数
 * 
 * @returns 引擎实例
 * 
 * @example
 * ```typescript
 * import { LitElement, html } from 'lit'
 * import { useEngine } from '@ldesign/engine-lit'
 * 
 * export class MyComponent extends LitElement {
 *   engine = useEngine()
 * 
 *   render() {
 *     return html`
 *       <div>Count: ${this.engine.state.get('count')}</div>
 *     `
 *   }
 * }
 * ```
 */
export function useEngine(): CoreEngine {
  const engine = (window as any).__ldesignEngine as CoreEngine | undefined

  if (!engine) {
    throw new Error('Engine not found. Make sure you have called createEngineApp.')
  }

  return engine
}

/**
 * 获取引擎实例
 *
 * useEngine 的别名,用于与其他框架保持一致
 *
 * @returns 引擎实例
 *
 * @example
 * ```typescript
 * import { getEngine } from '@ldesign/engine-lit'
 *
 * const engine = getEngine()
 * ```
 */
export function getEngine(): CoreEngine {
  return useEngine()
}
