// packages/react/src/adapters/react-adapter.ts
/**
 * React 框架适配器
 * 
 * 提供 React 框架与核心引擎的集成,包括:
 * - React 应用创建和挂载
 * - 状态管理适配(使用 React hooks)
 * - 事件系统适配
 * - 生命周期映射
 * 
 * @module adapter
 */

import { createElement, type ComponentType, type ReactElement } from 'react'
import { createRoot, type Root } from 'react-dom/client'
import type {
  FrameworkAdapter,
  FrameworkInfo,
  StateAdapter,
  EventAdapter,
  LifecycleHookMap,
  CoreEngine,
  ReactiveState,
  Unsubscribe,
} from '@ldesign/engine-core'
import { EngineProvider } from '../hooks'

/**
 * React 框架信息
 */
const REACT_INFO: FrameworkInfo = {
  name: 'react',
  version: '18.x',
  features: {
    reactive: true,
    components: true,
    directives: false,
    slots: true,
  },
}

/**
 * React 状态适配器
 * 
 * 将核心引擎的状态管理适配到 React 的 hooks 系统
 * 
 * 注意: React 的响应式系统基于 hooks,与 Vue 的响应式系统不同
 * 这里提供的是一个简化的适配层,实际使用时建议配合 React hooks
 */
export class ReactStateAdapter implements StateAdapter {
  /**
   * 创建响应式状态
   * 
   * 注意: 在 React 中,响应式状态应该使用 useState hook
   * 这里提供的是一个兼容层
   * 
   * @param initialValue - 初始值
   * @returns 响应式状态对象
   */
  createReactiveState<T>(initialValue: T): ReactiveState<T> {
    let currentValue = initialValue
    const listeners = new Set<(value: T) => void>()

    return {
      get value() {
        return currentValue
      },
      set value(newValue: T) {
        if (currentValue !== newValue) {
          currentValue = newValue
          listeners.forEach(listener => listener(newValue))
        }
      },
      readonly() {
        return currentValue
      },
      update(updater: (prev: T) => T) {
        this.value = updater(currentValue)
      },
      reset() {
        this.value = initialValue
      },
    }
  }

  /**
   * 监听状态变化
   * 
   * @param getter - 获取状态的函数
   * @param callback - 状态变化回调
   * @returns 取消监听函数
   */
  watch<T>(getter: () => T, callback: (value: T, oldValue?: T) => void): Unsubscribe {
    let oldValue = getter()
    
    // 使用轮询检测变化(简化实现)
    // 实际使用时建议使用 React 的 useEffect
    const timer = setInterval(() => {
      const newValue = getter()
      if (newValue !== oldValue) {
        callback(newValue, oldValue)
        oldValue = newValue
      }
    }, 100)

    return () => clearInterval(timer)
  }

  /**
   * 批量更新
   * 
   * React 18+ 自动批量更新,这里直接执行即可
   * 
   * @param fn - 批量更新函数
   */
  batch(fn: () => void): void {
    fn()
  }

  /**
   * 计算属性
   * 
   * @param getter - 计算函数
   * @returns 响应式状态对象
   */
  computed<T>(getter: () => T): ReactiveState<T> {
    const state = this.createReactiveState(getter())
    
    // 简化实现: 实际使用时建议使用 useMemo
    setInterval(() => {
      state.value = getter()
    }, 100)

    return state
  }
}

/**
 * React 事件适配器
 * 
 * 提供与核心引擎事件系统兼容的事件接口
 */
export class ReactEventAdapter implements EventAdapter {
  private handlers = new Map<string, Set<(payload: any) => void>>()

  /**
   * 触发事件
   * 
   * @param event - 事件名称
   * @param payload - 事件数据
   */
  emit(event: string, payload?: any): void {
    const eventHandlers = this.handlers.get(event)
    if (eventHandlers) {
      eventHandlers.forEach(handler => {
        try {
          handler(payload)
        } catch (error) {
          console.error(`Error in React event handler for "${event}":`, error)
        }
      })
    }
  }

  /**
   * 监听事件
   * 
   * @param event - 事件名称
   * @param handler - 事件处理函数
   * @returns 取消监听函数
   */
  on(event: string, handler: (payload: any) => void): Unsubscribe {
    if (!this.handlers.has(event)) {
      this.handlers.set(event, new Set())
    }
    this.handlers.get(event)!.add(handler)

    return () => this.off(event, handler)
  }

  /**
   * 一次性监听
   * 
   * @param event - 事件名称
   * @param handler - 事件处理函数
   * @returns 取消监听函数
   */
  once(event: string, handler: (payload: any) => void): Unsubscribe {
    const wrappedHandler = (payload: any) => {
      handler(payload)
      this.off(event, wrappedHandler)
    }
    return this.on(event, wrappedHandler)
  }

  /**
   * 移除事件监听
   * 
   * @param event - 事件名称
   * @param handler - 事件处理函数
   */
  off(event: string, handler?: (payload: any) => void): void {
    if (!handler) {
      this.handlers.delete(event)
    } else {
      this.handlers.get(event)?.delete(handler)
    }
  }
}

/**
 * React 框架适配器
 * 
 * 提供 React 应用的创建、挂载和引擎集成
 * 
 * @example
 * ```typescript
 * const adapter = new ReactAdapter()
 * const root = adapter.createApp(App)
 * await adapter.mount(root, '#app')
 * ```
 */
export class ReactAdapter implements FrameworkAdapter<Root, ComponentType> {
  readonly info = REACT_INFO
  
  /** 存储引擎实例的 Map,用于在组件中访问 */
  private engineMap = new WeakMap<Root, CoreEngine>()

  /**
   * 创建 React 应用
   * 
   * @param rootComponent - 根组件
   * @param options - 创建选项
   * @returns React Root 实例
   */
  createApp(rootComponent: ComponentType, options?: any): Root {
    // 注意: 实际的 Root 创建在 mount 时进行
    // 这里返回一个占位对象
    return { rootComponent, options } as any
  }

  /**
   * 挂载应用
   *
   * @param app - React Root 实例
   * @param mountElement - 挂载元素
   */
  async mount(app: Root, mountElement: string | Element): Promise<void> {
    const container = typeof mountElement === 'string'
      ? document.querySelector(mountElement)
      : mountElement

    if (!container) {
      throw new Error(`Mount element not found: ${mountElement}`)
    }

    // 创建 React Root
    const root = createRoot(container)

    // 获取根组件和选项
    const { rootComponent, options } = app as any

    // 获取引擎实例
    const engine = this.engineMap.get(app)

    if (!engine) {
      throw new Error('Engine not registered. Call registerEngine before mount.')
    }

    // 渲染应用 - 用 EngineProvider 包裹
    const element = createElement(
      EngineProvider,
      { engine },
      createElement(rootComponent, options)
    )
    root.render(element)

    // 保存 root 引用
    Object.assign(app, root)
  }

  /**
   * 卸载应用
   * 
   * @param app - React Root 实例
   */
  async unmount(app: Root): Promise<void> {
    app.unmount()
  }

  /**
   * 注册引擎到应用
   * 
   * 在 React 中,引擎通过 Context 提供给组件
   * 
   * @param app - React Root 实例
   * @param engine - 核心引擎实例
   */
  registerEngine(app: Root, engine: CoreEngine): void {
    this.engineMap.set(app, engine)
  }

  /**
   * 创建状态适配器
   * 
   * @returns 状态适配器实例
   */
  createStateAdapter(): StateAdapter {
    return new ReactStateAdapter()
  }

  /**
   * 创建事件适配器
   * 
   * @returns 事件适配器实例
   */
  createEventAdapter(): EventAdapter {
    return new ReactEventAdapter()
  }

  /**
   * 映射生命周期钩子
   * 
   * React 的生命周期与 Vue 不同,这里提供一个映射
   * 
   * @returns 生命周期钩子映射
   */
  mapLifecycleHooks(): LifecycleHookMap {
    return {
      beforeMount: 'useEffect-setup',
      mounted: 'useEffect-mounted',
      beforeUpdate: 'useEffect-before-update',
      updated: 'useEffect-updated',
      beforeUnmount: 'useEffect-cleanup',
      unmounted: 'useEffect-unmounted',
    }
  }
}

/**
 * 创建 React 适配器实例
 * 
 * @returns React 适配器实例
 * 
 * @example
 * ```typescript
 * import { createReactAdapter } from '@ldesign/engine-react'
 * 
 * const adapter = createReactAdapter()
 * ```
 */
export function createReactAdapter(): ReactAdapter {
  return new ReactAdapter()
}

// packages/solid/src/adapter.ts
/**
 * Solid.js 框架适配器
 * 
 * 支持 Solid.js 1.8+
 */

import { createSignal, createEffect, createMemo, onCleanup } from 'solid-js'
import { render } from 'solid-js/web'
import type {
  FrameworkAdapter,
  FrameworkInfo,
  StateAdapter,
  EventAdapter,
  LifecycleHookMap,
  CoreEngine,
  ReactiveState,
  Unsubscribe,
} from '@ldesign/engine-core'

/**
 * Solid.js 框架信息
 */
const SOLID_INFO: FrameworkInfo = {
  name: 'solid',
  version: '1.8+',
  features: {
    reactive: true,
    components: true,
    directives: true,
    slots: false,
  },
}

/**
 * Solid 状态适配器
 * 
 * 使用 Solid signals 实现响应式状态管理
 */
class SolidStateAdapter implements StateAdapter {
  /**
   * 创建响应式状态
   * 
   * @param initialValue - 初始值
   * @returns 响应式状态对象
   */
  createReactiveState<T>(initialValue: T): ReactiveState<T> {
    const [get, set] = createSignal(initialValue)
    const initial = JSON.parse(JSON.stringify(initialValue))

    return {
      get value() {
        return get()
      },
      set value(newValue: T) {
        set(() => newValue)
      },
      readonly() {
        return get()
      },
      update(updater: (prev: T) => T) {
        set(updater)
      },
      reset() {
        set(() => JSON.parse(JSON.stringify(initial)))
      },
      // 暴露 Solid signal 以便在组件中使用
      signal: [get, set],
    } as ReactiveState<T> & { signal: [() => T, (value: T | ((prev: T) => T)) => void] }
  }

  /**
   * 监听状态变化
   * 
   * @param getter - 获取状态的函数
   * @param callback - 状态变化时的回调函数
   * @returns 取消监听的函数
   */
  watch<T>(getter: () => T, callback: (value: T, oldValue?: T) => void): Unsubscribe {
    let oldValue: T | undefined
    let isFirst = true

    const dispose = createEffect(() => {
      const value = getter()
      if (!isFirst) {
        callback(value, oldValue)
      }
      oldValue = value
      isFirst = false
    })

    return dispose
  }

  /**
   * 批量更新状态
   * 
   * Solid 自动批量更新,所以直接执行函数即可
   * 
   * @param fn - 批量更新函数
   */
  batch(fn: () => void): void {
    fn()
  }

  /**
   * 创建计算属性
   * 
   * @param getter - 计算函数
   * @returns 只读的响应式状态
   */
  computed<T>(getter: () => T): ReactiveState<T> {
    const memo = createMemo(getter)

    return {
      get value() {
        return memo()
      },
      set value(_newValue: T) {
        console.warn('Cannot set computed property')
      },
      readonly() {
        return memo()
      },
      update(_updater: (prev: T) => T) {
        console.warn('Cannot update computed property')
      },
      // 暴露 Solid memo
      memo,
    } as ReactiveState<T> & { memo: () => T }
  }
}

/**
 * Solid 事件适配器
 * 
 * 使用简单的发布订阅模式实现事件系统
 */
class SolidEventAdapter implements EventAdapter {
  private listeners = new Map<string, Set<(payload: any) => void>>()

  /**
   * 触发事件
   * 
   * @param event - 事件名称
   * @param payload - 事件数据
   */
  emit(event: string, payload?: any): void {
    const handlers = this.listeners.get(event)
    if (handlers) {
      handlers.forEach((handler) => handler(payload))
    }
  }

  /**
   * 监听事件
   * 
   * @param event - 事件名称
   * @param handler - 事件处理函数
   * @returns 取消监听的函数
   */
  on(event: string, handler: (payload: any) => void): Unsubscribe {
    if (!this.listeners.has(event)) {
      this.listeners.set(event, new Set())
    }
    this.listeners.get(event)!.add(handler)

    return () => {
      const handlers = this.listeners.get(event)
      if (handlers) {
        handlers.delete(handler)
        if (handlers.size === 0) {
          this.listeners.delete(event)
        }
      }
    }
  }

  /**
   * 监听事件一次
   * 
   * @param event - 事件名称
   * @param handler - 事件处理函数
   * @returns 取消监听的函数
   */
  once(event: string, handler: (payload: any) => void): Unsubscribe {
    const wrapper = (payload: any) => {
      handler(payload)
      this.off(event, wrapper)
    }
    return this.on(event, wrapper)
  }

  /**
   * 取消监听事件
   * 
   * @param event - 事件名称
   * @param handler - 事件处理函数(可选)
   */
  off(event: string, handler?: (payload: any) => void): void {
    if (handler) {
      const handlers = this.listeners.get(event)
      if (handlers) {
        handlers.delete(handler)
        if (handlers.size === 0) {
          this.listeners.delete(event)
        }
      }
    } else {
      this.listeners.delete(event)
    }
  }
}

/**
 * Solid 框架适配器
 */
export class SolidAdapter implements FrameworkAdapter<any, any> {
  readonly info = SOLID_INFO
  private engineSignal = createSignal<CoreEngine | null>(null)
  private disposeApp: (() => void) | null = null

  /**
   * 创建 Solid 应用
   * 
   * @param rootComponent - 根组件
   * @param options - 应用选项
   * @returns Solid 应用实例
   */
  createApp(rootComponent: any, options?: any): any {
    return {
      component: rootComponent,
      options: options || {},
    }
  }

  /**
   * 挂载应用
   * 
   * @param app - Solid 应用实例
   * @param mountElement - 挂载元素
   */
  async mount(app: any, mountElement: string | Element): Promise<void> {
    const target = typeof mountElement === 'string'
      ? document.querySelector(mountElement)
      : mountElement

    if (!target) {
      throw new Error(`Mount element not found: ${mountElement}`)
    }

    // 使用 Solid 的 render 函数挂载组件
    this.disposeApp = render(() => app.component(app.options.props || {}), target)
  }

  /**
   * 卸载应用
   * 
   * @param app - Solid 应用实例
   */
  async unmount(app: any): Promise<void> {
    if (this.disposeApp) {
      this.disposeApp()
      this.disposeApp = null
    }
    console.log('Solid app unmounted')
  }

  /**
   * 注册引擎到 Solid
   * 
   * @param app - Solid 应用实例
   * @param engine - 核心引擎实例
   */
  registerEngine(app: any, engine: CoreEngine): void {
    // 将引擎存储到 signal 中
    const [, setEngine] = this.engineSignal
    setEngine(() => engine)
    
    // 将引擎添加到应用选项中
    if (!app.options.props) {
      app.options.props = {}
    }
    app.options.props.engine = engine
  }

  /**
   * 获取引擎 signal
   * 
   * @returns 引擎 signal
   */
  getEngineSignal() {
    return this.engineSignal
  }

  /**
   * 创建状态适配器
   * 
   * @returns 状态适配器实例
   */
  createStateAdapter(): StateAdapter {
    return new SolidStateAdapter()
  }

  /**
   * 创建事件适配器
   * 
   * @returns 事件适配器实例
   */
  createEventAdapter(): EventAdapter {
    return new SolidEventAdapter()
  }

  /**
   * 映射生命周期钩子
   * 
   * @returns 生命周期钩子映射
   */
  mapLifecycleHooks(): LifecycleHookMap {
    return {
      beforeMount: 'beforeMount',
      mounted: 'onMount',
      beforeUpdate: 'beforeUpdate',
      updated: 'onCleanup',
      beforeUnmount: 'onCleanup',
      unmounted: 'onCleanup',
    }
  }

  /**
   * 注册组件
   * 
   * Solid 不需要全局注册组件
   * 
   * @param app - Solid 应用实例
   * @param name - 组件名称
   * @param component - 组件
   */
  registerComponent(app: any, name: string, component: any): void {
    console.log(`Solid component registered: ${name}`)
  }

  /**
   * 注册指令
   * 
   * Solid 使用 directives
   * 
   * @param app - Solid 应用实例
   * @param name - 指令名称
   * @param directive - 指令
   */
  registerDirective(app: any, name: string, directive: any): void {
    console.log(`Solid directive registered: ${name}`)
  }

  /**
   * 提供全局属性
   * 
   * Solid 通过 context 提供全局属性
   * 
   * @param app - Solid 应用实例
   * @param key - 属性键
   * @param value - 属性值
   */
  provideGlobalProperty(app: any, key: string, value: any): void {
    if (!app.options.context) {
      app.options.context = new Map()
    }
    app.options.context.set(key, value)
  }
}

/**
 * 创建 Solid 适配器
 * 
 * @returns Solid 适配器实例
 */
export function createSolidAdapter(): SolidAdapter {
  return new SolidAdapter()
}
