// packages/react/example/src/components/RouterView.tsx
import React, { useEffect, useState } from 'react'
import { useEngine } from '@ldesign/engine-react'

interface RouterViewProps {
  routes: Array<{
    path: string
    component: React.ComponentType
  }>
}

function RouterView({ routes }: RouterViewProps) {
  const engine = useEngine()
  const [currentPath, setCurrentPath] = useState('/')
  const [CurrentComponent, setCurrentComponent] = useState<React.ComponentType | null>(null)

  useEffect(() => {
    const updateRoute = () => {
      // 直接从window.location获取当前路径
      const path = window.location.pathname
      console.log('[RouterView] updateRoute called, path:', path)
      setCurrentPath(path)

      // 查找匹配的路由
      const matchedRoute = routes.find(r => {
        if (r.path === path) return true
        // 简单的参数匹配（例如 /user/:id）
        const pathPattern = r.path.replace(/:\w+/g, '[^/]+')
        const regex = new RegExp(`^${pathPattern}$`)
        return regex.test(path)
      })

      console.log('[RouterView] matchedRoute:', matchedRoute)

      if (matchedRoute) {
        setCurrentComponent(() => matchedRoute.component)
      } else {
        setCurrentComponent(null)
      }
    }

    updateRoute()

    // 监听路由变化 - 使用多种方式
    console.log('[RouterView] Setting up route listeners')

    // 1. 监听engine的router:navigated事件
    const unsubscribeEngine = engine.events.on('router:navigated', (data) => {
      console.log('[RouterView] router:navigated event received:', data)
      updateRoute()
    })

    // 2. 监听浏览器的popstate事件（处理浏览器前进/后退）
    const handlePopState = () => {
      console.log('[RouterView] popstate event')
      updateRoute()
    }
    window.addEventListener('popstate', handlePopState)

    // 3. 使用MutationObserver监听URL变化（处理pushState/replaceState）
    let lastPath = window.location.pathname
    const checkPathChange = () => {
      const currentPath = window.location.pathname
      if (currentPath !== lastPath) {
        console.log('[RouterView] Path changed from', lastPath, 'to', currentPath)
        lastPath = currentPath
        updateRoute()
      }
    }
    const intervalId = setInterval(checkPathChange, 100)

    return () => {
      unsubscribeEngine()
      window.removeEventListener('popstate', handlePopState)
      clearInterval(intervalId)
    }
  }, [engine, routes])

  if (!CurrentComponent) {
    return (
      <div className="page">
        <h2>404 - 页面未找到</h2>
        <p>路径: {currentPath}</p>
      </div>
    )
  }

  return <CurrentComponent />
}

export default RouterView

// packages/vue3/example/src/components/RouterView.vue
<template>
  <component :is="currentComponent" v-if="currentComponent" />
  <div v-else class="page">
    <h2>404 - 页面未找到</h2>
    <p>路径: {{ currentPath }}</p>
  </div>
</template>

<script setup lang="ts">
import { ref, onMounted, onUnmounted, type Component } from 'vue'
import { useEngine } from '@ldesign/engine-vue3'

interface Route {
  path: string
  component: Component
}

const props = defineProps<{
  routes: Route[]
}>()

const engine = useEngine()
const currentPath = ref('/')
const currentComponent = ref<Component | null>(null)

const updateRoute = () => {
  if (!engine.router) {
    console.warn('Router not available in engine')
    return
  }

  const route = engine.router.getCurrentRoute()
  const path = route.value?.path || '/'
  currentPath.value = path

  // 查找匹配的路由
  const matchedRoute = props.routes.find(r => {
    if (r.path === path) return true
    // 简单的参数匹配（例如 /user/:id）
    const pathPattern = r.path.replace(/:\w+/g, '[^/]+')
    const regex = new RegExp(`^${pathPattern}$`)
    return regex.test(path)
  })

  if (matchedRoute) {
    currentComponent.value = matchedRoute.component
  } else {
    currentComponent.value = null
  }
}

onMounted(() => {
  updateRoute()
  // 监听路由变化
  engine.events.on('router:navigated', updateRoute)
})

onUnmounted(() => {
  engine.events.off('router:navigated', updateRoute)
})
</script>

<style scoped>
.page {
  animation: fadeIn 0.3s ease-in;
}

@keyframes fadeIn {
  from {
    opacity: 0;
    transform: translateY(10px);
  }
  to {
    opacity: 1;
    transform: translateY(0);
  }
}
</style>
