// packages/vue2/example/src/components/Navigation.vue
<template>
  <nav class="navigation">
    <div class="nav-brand">
      <span class="logo">🚀</span>
      <span class="brand-name">LDesign Engine</span>
      <span class="framework-badge">Vue 2</span>
    </div>
    <div class="nav-links">
      <a
        v-for="link in links"
        :key="link.path"
        :href="link.path"
        :class="{ active: isActive(link.path) }"
        @click.prevent="navigate(link.path)"
      >
        {{ link.label }}
      </a>
    </div>
  </nav>
</template>

<script>
import { getEngine } from '@ldesign/engine-vue2'

export default {
  name: 'Navigation',
  data() {
    return {
      currentPath: '/',
      links: [
        { path: '/', label: '首页' },
        { path: '/about', label: '关于' },
        { path: '/user/1', label: '用户' },
      ],
      unsubscribe: null,
    }
  },
  created() {
    const engine = getEngine()
    if (engine.router) {
      const route = engine.router.getCurrentRoute()
      this.currentPath = route.value?.path || '/'
      
      this.unsubscribe = engine.events.on('router:navigated', () => {
        if (engine.router) {
          const route = engine.router.getCurrentRoute()
          this.currentPath = route.value?.path || '/'
        }
      })
    }
  },
  beforeDestroy() {
    if (this.unsubscribe) {
      this.unsubscribe()
    }
  },
  methods: {
    navigate(path) {
      const engine = getEngine()
      if (engine.router) {
        engine.router.push(path)
      }
    },
    isActive(path) {
      if (path === '/') {
        return this.currentPath === '/'
      }
      return this.currentPath.startsWith(path)
    },
  },
}
</script>

<style scoped>
.navigation {
  display: flex;
  justify-content: space-between;
  align-items: center;
  padding: 1rem 2rem;
  background: white;
  box-shadow: 0 2px 8px rgba(0, 0, 0, 0.1);
  margin-bottom: 2rem;
}

.nav-brand {
  display: flex;
  align-items: center;
  gap: 0.75rem;
}

.logo {
  font-size: 1.5rem;
}

.brand-name {
  font-size: 1.25rem;
  font-weight: bold;
  color: #333;
}

.framework-badge {
  padding: 0.25rem 0.75rem;
  background: #667eea;
  color: white;
  border-radius: 12px;
  font-size: 0.75rem;
  font-weight: 600;
}

.nav-links {
  display: flex;
  gap: 1.5rem;
}

.nav-links a {
  text-decoration: none;
  color: #666;
  font-weight: 500;
  padding: 0.5rem 1rem;
  border-radius: 6px;
  transition: all 0.3s;
}

.nav-links a:hover {
  color: #667eea;
  background: #f3f4f6;
}

.nav-links a.active {
  color: #667eea;
  background: #eef2ff;
}
</style>

// packages/qwik/example/src/components/Navigation.tsx
import { component$, useSignal, useVisibleTask$, $ } from '@builder.io/qwik'
import { getEngine } from '@ldesign/engine-qwik'

export default component$(() => {
  const currentPath = useSignal('/')

  useVisibleTask$(() => {
    try {
      const engine = getEngine()
      if (engine.router) {
        const route = engine.router.getCurrentRoute()
        currentPath.value = route.value?.path || '/'

        const unsubscribe = engine.events.on('router:navigated', () => {
          if (engine.router) {
            const route = engine.router.getCurrentRoute()
            currentPath.value = route.value?.path || '/'
          }
        })
        return () => unsubscribe()
      }
    } catch (error) {
      console.warn('Engine not ready yet:', error)
    }
  })

  const navigate = $((path: string, event: Event) => {
    event.preventDefault()
    try {
      const engine = getEngine()
      if (engine.router) {
        engine.router.push(path)
      }
    } catch (error) {
      console.warn('Engine not ready:', error)
    }
  })

  const isActive = (path: string) => {
    return currentPath.value === path || currentPath.value.startsWith(path + '/')
  }

  return (
    <nav class="navigation">
      <div class="nav-container">
        <div class="nav-brand">
          <h1>🚀 Qwik + LDesign Engine</h1>
        </div>
        <div class="nav-links">
          <a
            href="/"
            class={isActive('/') && !isActive('/user') && !isActive('/about') ? 'nav-link active' : 'nav-link'}
            onClick$={(e) => navigate('/', e)}
          >
            🏠 首页
          </a>
          <a
            href="/about"
            class={isActive('/about') ? 'nav-link active' : 'nav-link'}
            onClick$={(e) => navigate('/about', e)}
          >
            ℹ️ 关于
          </a>
          <a
            href="/user/1"
            class={isActive('/user') ? 'nav-link active' : 'nav-link'}
            onClick$={(e) => navigate('/user/1', e)}
          >
            👤 用户
          </a>
        </div>
      </div>

      <style>{`
        .navigation {
          background: white;
          box-shadow: 0 2px 8px rgba(0, 0, 0, 0.1);
          position: sticky;
          top: 0;
          z-index: 100;
        }

        .nav-container {
          max-width: 1200px;
          margin: 0 auto;
          padding: 1rem 2rem;
          display: flex;
          justify-content: space-between;
          align-items: center;
        }

        .nav-brand h1 {
          margin: 0;
          font-size: 1.5rem;
          background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
          -webkit-background-clip: text;
          -webkit-text-fill-color: transparent;
          background-clip: text;
        }

        .nav-links {
          display: flex;
          gap: 1rem;
        }

        .nav-link {
          padding: 0.75rem 1.5rem;
          text-decoration: none;
          color: #666;
          border-radius: 6px;
          transition: all 0.3s;
          font-weight: 500;
        }

        .nav-link:hover {
          background: #f3f4f6;
          color: #333;
        }

        .nav-link.active {
          background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
          color: white;
        }

        @media (max-width: 768px) {
          .nav-container {
            flex-direction: column;
            gap: 1rem;
          }

          .nav-links {
            width: 100%;
            justify-content: center;
          }

          .nav-link {
            flex: 1;
            text-align: center;
          }
        }
      `}</style>
    </nav>
  )
})
